version: '3.8'

services:
  encareapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__MongoDB=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - encare-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - encare-network
    volumes:
      - mongo-data:/data/db

networks:
  encare-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
