using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace EncareAPI.Models
{public class User
{
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; } = null!; // Auto-generated by MongoDB

    public string GoogleId { get; set; } = null!; // Unique Google ID
    public string Email { get; set; } = null!;

    [BsonElement("passwordHash")]
    public string PasswordHash { get; set; } // Store hashed passwords

    public string Name { get; set; } = null!;

    [BsonElement("Gender")]
    public string Gender { get; set; }

    [BsonElement("Phone")]
    public string? Phone { get; set; } = null!;

    public DateTime? Birthday { get; set; }

    [BsonElement("Weight")]
    public double? Weight { get; set; } // น้ำหนัก (kg)

    [BsonElement("Height")]
    public double? Height { get; set; } // ส่วนสูง (cm)
}

}